// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temporalAgg.protoc

package com.hbase.protoc;

public final class TemporalAgg {
  private TemporalAgg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TemporalAggRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string rowkey = 1;
    /**
     * <code>required string rowkey = 1;</code>
     */
    boolean hasRowkey();
    /**
     * <code>required string rowkey = 1;</code>
     */
    java.lang.String getRowkey();
    /**
     * <code>required string rowkey = 1;</code>
     */
    com.google.protobuf.ByteString
        getRowkeyBytes();

    // required string cateList = 2;
    /**
     * <code>required string cateList = 2;</code>
     */
    boolean hasCateList();
    /**
     * <code>required string cateList = 2;</code>
     */
    java.lang.String getCateList();
    /**
     * <code>required string cateList = 2;</code>
     */
    com.google.protobuf.ByteString
        getCateListBytes();

    // required string startTime = 3;
    /**
     * <code>required string startTime = 3;</code>
     */
    boolean hasStartTime();
    /**
     * <code>required string startTime = 3;</code>
     */
    java.lang.String getStartTime();
    /**
     * <code>required string startTime = 3;</code>
     */
    com.google.protobuf.ByteString
        getStartTimeBytes();

    // required string endTime = 4;
    /**
     * <code>required string endTime = 4;</code>
     */
    boolean hasEndTime();
    /**
     * <code>required string endTime = 4;</code>
     */
    java.lang.String getEndTime();
    /**
     * <code>required string endTime = 4;</code>
     */
    com.google.protobuf.ByteString
        getEndTimeBytes();
  }
  /**
   * Protobuf type {@code TemporalAggRequest}
   */
  public static final class TemporalAggRequest extends
      com.google.protobuf.GeneratedMessage
      implements TemporalAggRequestOrBuilder {
    // Use TemporalAggRequest.newBuilder() to construct.
    private TemporalAggRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TemporalAggRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TemporalAggRequest defaultInstance;
    public static TemporalAggRequest getDefaultInstance() {
      return defaultInstance;
    }

    public TemporalAggRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TemporalAggRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              rowkey_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              cateList_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              startTime_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              endTime_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hbase.protoc.TemporalAgg.internal_static_TemporalAggRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hbase.protoc.TemporalAgg.internal_static_TemporalAggRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hbase.protoc.TemporalAgg.TemporalAggRequest.class, com.hbase.protoc.TemporalAgg.TemporalAggRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<TemporalAggRequest> PARSER =
        new com.google.protobuf.AbstractParser<TemporalAggRequest>() {
      public TemporalAggRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TemporalAggRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TemporalAggRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string rowkey = 1;
    public static final int ROWKEY_FIELD_NUMBER = 1;
    private java.lang.Object rowkey_;
    /**
     * <code>required string rowkey = 1;</code>
     */
    public boolean hasRowkey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string rowkey = 1;</code>
     */
    public java.lang.String getRowkey() {
      java.lang.Object ref = rowkey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          rowkey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string rowkey = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRowkeyBytes() {
      java.lang.Object ref = rowkey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rowkey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string cateList = 2;
    public static final int CATELIST_FIELD_NUMBER = 2;
    private java.lang.Object cateList_;
    /**
     * <code>required string cateList = 2;</code>
     */
    public boolean hasCateList() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string cateList = 2;</code>
     */
    public java.lang.String getCateList() {
      java.lang.Object ref = cateList_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cateList_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string cateList = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCateListBytes() {
      java.lang.Object ref = cateList_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cateList_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string startTime = 3;
    public static final int STARTTIME_FIELD_NUMBER = 3;
    private java.lang.Object startTime_;
    /**
     * <code>required string startTime = 3;</code>
     */
    public boolean hasStartTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string startTime = 3;</code>
     */
    public java.lang.String getStartTime() {
      java.lang.Object ref = startTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          startTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string startTime = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStartTimeBytes() {
      java.lang.Object ref = startTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string endTime = 4;
    public static final int ENDTIME_FIELD_NUMBER = 4;
    private java.lang.Object endTime_;
    /**
     * <code>required string endTime = 4;</code>
     */
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string endTime = 4;</code>
     */
    public java.lang.String getEndTime() {
      java.lang.Object ref = endTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          endTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string endTime = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEndTimeBytes() {
      java.lang.Object ref = endTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      rowkey_ = "";
      cateList_ = "";
      startTime_ = "";
      endTime_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRowkey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCateList()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStartTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEndTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRowkeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCateListBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getStartTimeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getEndTimeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRowkeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCateListBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getStartTimeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getEndTimeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hbase.protoc.TemporalAgg.TemporalAggRequest)) {
        return super.equals(obj);
      }
      com.hbase.protoc.TemporalAgg.TemporalAggRequest other = (com.hbase.protoc.TemporalAgg.TemporalAggRequest) obj;

      boolean result = true;
      result = result && (hasRowkey() == other.hasRowkey());
      if (hasRowkey()) {
        result = result && getRowkey()
            .equals(other.getRowkey());
      }
      result = result && (hasCateList() == other.hasCateList());
      if (hasCateList()) {
        result = result && getCateList()
            .equals(other.getCateList());
      }
      result = result && (hasStartTime() == other.hasStartTime());
      if (hasStartTime()) {
        result = result && getStartTime()
            .equals(other.getStartTime());
      }
      result = result && (hasEndTime() == other.hasEndTime());
      if (hasEndTime()) {
        result = result && getEndTime()
            .equals(other.getEndTime());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasRowkey()) {
        hash = (37 * hash) + ROWKEY_FIELD_NUMBER;
        hash = (53 * hash) + getRowkey().hashCode();
      }
      if (hasCateList()) {
        hash = (37 * hash) + CATELIST_FIELD_NUMBER;
        hash = (53 * hash) + getCateList().hashCode();
      }
      if (hasStartTime()) {
        hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
        hash = (53 * hash) + getStartTime().hashCode();
      }
      if (hasEndTime()) {
        hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
        hash = (53 * hash) + getEndTime().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hbase.protoc.TemporalAgg.TemporalAggRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.protoc.TemporalAgg.TemporalAggRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.protoc.TemporalAgg.TemporalAggRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.protoc.TemporalAgg.TemporalAggRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.protoc.TemporalAgg.TemporalAggRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.protoc.TemporalAgg.TemporalAggRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hbase.protoc.TemporalAgg.TemporalAggRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hbase.protoc.TemporalAgg.TemporalAggRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hbase.protoc.TemporalAgg.TemporalAggRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.protoc.TemporalAgg.TemporalAggRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hbase.protoc.TemporalAgg.TemporalAggRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TemporalAggRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hbase.protoc.TemporalAgg.TemporalAggRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hbase.protoc.TemporalAgg.internal_static_TemporalAggRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hbase.protoc.TemporalAgg.internal_static_TemporalAggRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hbase.protoc.TemporalAgg.TemporalAggRequest.class, com.hbase.protoc.TemporalAgg.TemporalAggRequest.Builder.class);
      }

      // Construct using com.hbase.protoc.TemporalAgg.TemporalAggRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rowkey_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        cateList_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        startTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        endTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hbase.protoc.TemporalAgg.internal_static_TemporalAggRequest_descriptor;
      }

      public com.hbase.protoc.TemporalAgg.TemporalAggRequest getDefaultInstanceForType() {
        return com.hbase.protoc.TemporalAgg.TemporalAggRequest.getDefaultInstance();
      }

      public com.hbase.protoc.TemporalAgg.TemporalAggRequest build() {
        com.hbase.protoc.TemporalAgg.TemporalAggRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hbase.protoc.TemporalAgg.TemporalAggRequest buildPartial() {
        com.hbase.protoc.TemporalAgg.TemporalAggRequest result = new com.hbase.protoc.TemporalAgg.TemporalAggRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rowkey_ = rowkey_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cateList_ = cateList_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.startTime_ = startTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.endTime_ = endTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hbase.protoc.TemporalAgg.TemporalAggRequest) {
          return mergeFrom((com.hbase.protoc.TemporalAgg.TemporalAggRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hbase.protoc.TemporalAgg.TemporalAggRequest other) {
        if (other == com.hbase.protoc.TemporalAgg.TemporalAggRequest.getDefaultInstance()) return this;
        if (other.hasRowkey()) {
          bitField0_ |= 0x00000001;
          rowkey_ = other.rowkey_;
          onChanged();
        }
        if (other.hasCateList()) {
          bitField0_ |= 0x00000002;
          cateList_ = other.cateList_;
          onChanged();
        }
        if (other.hasStartTime()) {
          bitField0_ |= 0x00000004;
          startTime_ = other.startTime_;
          onChanged();
        }
        if (other.hasEndTime()) {
          bitField0_ |= 0x00000008;
          endTime_ = other.endTime_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRowkey()) {
          
          return false;
        }
        if (!hasCateList()) {
          
          return false;
        }
        if (!hasStartTime()) {
          
          return false;
        }
        if (!hasEndTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hbase.protoc.TemporalAgg.TemporalAggRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hbase.protoc.TemporalAgg.TemporalAggRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string rowkey = 1;
      private java.lang.Object rowkey_ = "";
      /**
       * <code>required string rowkey = 1;</code>
       */
      public boolean hasRowkey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string rowkey = 1;</code>
       */
      public java.lang.String getRowkey() {
        java.lang.Object ref = rowkey_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          rowkey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string rowkey = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRowkeyBytes() {
        java.lang.Object ref = rowkey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rowkey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string rowkey = 1;</code>
       */
      public Builder setRowkey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        rowkey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string rowkey = 1;</code>
       */
      public Builder clearRowkey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rowkey_ = getDefaultInstance().getRowkey();
        onChanged();
        return this;
      }
      /**
       * <code>required string rowkey = 1;</code>
       */
      public Builder setRowkeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        rowkey_ = value;
        onChanged();
        return this;
      }

      // required string cateList = 2;
      private java.lang.Object cateList_ = "";
      /**
       * <code>required string cateList = 2;</code>
       */
      public boolean hasCateList() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string cateList = 2;</code>
       */
      public java.lang.String getCateList() {
        java.lang.Object ref = cateList_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          cateList_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string cateList = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCateListBytes() {
        java.lang.Object ref = cateList_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cateList_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string cateList = 2;</code>
       */
      public Builder setCateList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        cateList_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string cateList = 2;</code>
       */
      public Builder clearCateList() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cateList_ = getDefaultInstance().getCateList();
        onChanged();
        return this;
      }
      /**
       * <code>required string cateList = 2;</code>
       */
      public Builder setCateListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        cateList_ = value;
        onChanged();
        return this;
      }

      // required string startTime = 3;
      private java.lang.Object startTime_ = "";
      /**
       * <code>required string startTime = 3;</code>
       */
      public boolean hasStartTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string startTime = 3;</code>
       */
      public java.lang.String getStartTime() {
        java.lang.Object ref = startTime_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          startTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string startTime = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStartTimeBytes() {
        java.lang.Object ref = startTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          startTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string startTime = 3;</code>
       */
      public Builder setStartTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string startTime = 3;</code>
       */
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        startTime_ = getDefaultInstance().getStartTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string startTime = 3;</code>
       */
      public Builder setStartTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        startTime_ = value;
        onChanged();
        return this;
      }

      // required string endTime = 4;
      private java.lang.Object endTime_ = "";
      /**
       * <code>required string endTime = 4;</code>
       */
      public boolean hasEndTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string endTime = 4;</code>
       */
      public java.lang.String getEndTime() {
        java.lang.Object ref = endTime_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          endTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string endTime = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEndTimeBytes() {
        java.lang.Object ref = endTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          endTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string endTime = 4;</code>
       */
      public Builder setEndTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string endTime = 4;</code>
       */
      public Builder clearEndTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        endTime_ = getDefaultInstance().getEndTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string endTime = 4;</code>
       */
      public Builder setEndTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        endTime_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TemporalAggRequest)
    }

    static {
      defaultInstance = new TemporalAggRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:TemporalAggRequest)
  }

  public interface TemporalAggResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .TemporalAggResponse.TimeMap timeMap = 1;
    /**
     * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
     */
    java.util.List<com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap> 
        getTimeMapList();
    /**
     * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
     */
    com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap getTimeMap(int index);
    /**
     * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
     */
    int getTimeMapCount();
    /**
     * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
     */
    java.util.List<? extends com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMapOrBuilder> 
        getTimeMapOrBuilderList();
    /**
     * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
     */
    com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMapOrBuilder getTimeMapOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code TemporalAggResponse}
   */
  public static final class TemporalAggResponse extends
      com.google.protobuf.GeneratedMessage
      implements TemporalAggResponseOrBuilder {
    // Use TemporalAggResponse.newBuilder() to construct.
    private TemporalAggResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TemporalAggResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TemporalAggResponse defaultInstance;
    public static TemporalAggResponse getDefaultInstance() {
      return defaultInstance;
    }

    public TemporalAggResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TemporalAggResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                timeMap_ = new java.util.ArrayList<com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap>();
                mutable_bitField0_ |= 0x00000001;
              }
              timeMap_.add(input.readMessage(com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          timeMap_ = java.util.Collections.unmodifiableList(timeMap_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hbase.protoc.TemporalAgg.internal_static_TemporalAggResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hbase.protoc.TemporalAgg.internal_static_TemporalAggResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hbase.protoc.TemporalAgg.TemporalAggResponse.class, com.hbase.protoc.TemporalAgg.TemporalAggResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<TemporalAggResponse> PARSER =
        new com.google.protobuf.AbstractParser<TemporalAggResponse>() {
      public TemporalAggResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TemporalAggResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TemporalAggResponse> getParserForType() {
      return PARSER;
    }

    public interface TimeMapOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional string key = 1;
      /**
       * <code>optional string key = 1;</code>
       */
      boolean hasKey();
      /**
       * <code>optional string key = 1;</code>
       */
      java.lang.String getKey();
      /**
       * <code>optional string key = 1;</code>
       */
      com.google.protobuf.ByteString
          getKeyBytes();

      // optional int64 value = 2;
      /**
       * <code>optional int64 value = 2;</code>
       */
      boolean hasValue();
      /**
       * <code>optional int64 value = 2;</code>
       */
      long getValue();
    }
    /**
     * Protobuf type {@code TemporalAggResponse.TimeMap}
     */
    public static final class TimeMap extends
        com.google.protobuf.GeneratedMessage
        implements TimeMapOrBuilder {
      // Use TimeMap.newBuilder() to construct.
      private TimeMap(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private TimeMap(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final TimeMap defaultInstance;
      public static TimeMap getDefaultInstance() {
        return defaultInstance;
      }

      public TimeMap getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private TimeMap(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                key_ = input.readBytes();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                value_ = input.readInt64();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hbase.protoc.TemporalAgg.internal_static_TemporalAggResponse_TimeMap_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hbase.protoc.TemporalAgg.internal_static_TemporalAggResponse_TimeMap_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap.class, com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap.Builder.class);
      }

      public static com.google.protobuf.Parser<TimeMap> PARSER =
          new com.google.protobuf.AbstractParser<TimeMap>() {
        public TimeMap parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new TimeMap(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<TimeMap> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional string key = 1;
      public static final int KEY_FIELD_NUMBER = 1;
      private java.lang.Object key_;
      /**
       * <code>optional string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional int64 value = 2;
      public static final int VALUE_FIELD_NUMBER = 2;
      private long value_;
      /**
       * <code>optional int64 value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 value = 2;</code>
       */
      public long getValue() {
        return value_;
      }

      private void initFields() {
        key_ = "";
        value_ = 0L;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt64(2, value_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, value_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap)) {
          return super.equals(obj);
        }
        com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap other = (com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap) obj;

        boolean result = true;
        result = result && (hasKey() == other.hasKey());
        if (hasKey()) {
          result = result && getKey()
              .equals(other.getKey());
        }
        result = result && (hasValue() == other.hasValue());
        if (hasValue()) {
          result = result && (getValue()
              == other.getValue());
        }
        result = result &&
            getUnknownFields().equals(other.getUnknownFields());
        return result;
      }

      private int memoizedHashCode = 0;
      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        if (hasKey()) {
          hash = (37 * hash) + KEY_FIELD_NUMBER;
          hash = (53 * hash) + getKey().hashCode();
        }
        if (hasValue()) {
          hash = (37 * hash) + VALUE_FIELD_NUMBER;
          hash = (53 * hash) + hashLong(getValue());
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code TemporalAggResponse.TimeMap}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMapOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.hbase.protoc.TemporalAgg.internal_static_TemporalAggResponse_TimeMap_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.hbase.protoc.TemporalAgg.internal_static_TemporalAggResponse_TimeMap_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap.class, com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap.Builder.class);
        }

        // Construct using com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          key_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.hbase.protoc.TemporalAgg.internal_static_TemporalAggResponse_TimeMap_descriptor;
        }

        public com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap getDefaultInstanceForType() {
          return com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap.getDefaultInstance();
        }

        public com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap build() {
          com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap buildPartial() {
          com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap result = new com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.key_ = key_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap) {
            return mergeFrom((com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap other) {
          if (other == com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap.getDefaultInstance()) return this;
          if (other.hasKey()) {
            bitField0_ |= 0x00000001;
            key_ = other.key_;
            onChanged();
          }
          if (other.hasValue()) {
            setValue(other.getValue());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional string key = 1;
        private java.lang.Object key_ = "";
        /**
         * <code>optional string key = 1;</code>
         */
        public boolean hasKey() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string key = 1;</code>
         */
        public java.lang.String getKey() {
          java.lang.Object ref = key_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            key_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string key = 1;</code>
         */
        public com.google.protobuf.ByteString
            getKeyBytes() {
          java.lang.Object ref = key_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            key_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string key = 1;</code>
         */
        public Builder setKey(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string key = 1;</code>
         */
        public Builder clearKey() {
          bitField0_ = (bitField0_ & ~0x00000001);
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }
        /**
         * <code>optional string key = 1;</code>
         */
        public Builder setKeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }

        // optional int64 value = 2;
        private long value_ ;
        /**
         * <code>optional int64 value = 2;</code>
         */
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional int64 value = 2;</code>
         */
        public long getValue() {
          return value_;
        }
        /**
         * <code>optional int64 value = 2;</code>
         */
        public Builder setValue(long value) {
          bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 value = 2;</code>
         */
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = 0L;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:TemporalAggResponse.TimeMap)
      }

      static {
        defaultInstance = new TimeMap(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:TemporalAggResponse.TimeMap)
    }

    // repeated .TemporalAggResponse.TimeMap timeMap = 1;
    public static final int TIMEMAP_FIELD_NUMBER = 1;
    private java.util.List<com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap> timeMap_;
    /**
     * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
     */
    public java.util.List<com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap> getTimeMapList() {
      return timeMap_;
    }
    /**
     * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
     */
    public java.util.List<? extends com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMapOrBuilder> 
        getTimeMapOrBuilderList() {
      return timeMap_;
    }
    /**
     * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
     */
    public int getTimeMapCount() {
      return timeMap_.size();
    }
    /**
     * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
     */
    public com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap getTimeMap(int index) {
      return timeMap_.get(index);
    }
    /**
     * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
     */
    public com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMapOrBuilder getTimeMapOrBuilder(
        int index) {
      return timeMap_.get(index);
    }

    private void initFields() {
      timeMap_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < timeMap_.size(); i++) {
        output.writeMessage(1, timeMap_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < timeMap_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, timeMap_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hbase.protoc.TemporalAgg.TemporalAggResponse)) {
        return super.equals(obj);
      }
      com.hbase.protoc.TemporalAgg.TemporalAggResponse other = (com.hbase.protoc.TemporalAgg.TemporalAggResponse) obj;

      boolean result = true;
      result = result && getTimeMapList()
          .equals(other.getTimeMapList());
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getTimeMapCount() > 0) {
        hash = (37 * hash) + TIMEMAP_FIELD_NUMBER;
        hash = (53 * hash) + getTimeMapList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hbase.protoc.TemporalAgg.TemporalAggResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.protoc.TemporalAgg.TemporalAggResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.protoc.TemporalAgg.TemporalAggResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.protoc.TemporalAgg.TemporalAggResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.protoc.TemporalAgg.TemporalAggResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.protoc.TemporalAgg.TemporalAggResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hbase.protoc.TemporalAgg.TemporalAggResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hbase.protoc.TemporalAgg.TemporalAggResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hbase.protoc.TemporalAgg.TemporalAggResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.protoc.TemporalAgg.TemporalAggResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hbase.protoc.TemporalAgg.TemporalAggResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TemporalAggResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hbase.protoc.TemporalAgg.TemporalAggResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hbase.protoc.TemporalAgg.internal_static_TemporalAggResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hbase.protoc.TemporalAgg.internal_static_TemporalAggResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hbase.protoc.TemporalAgg.TemporalAggResponse.class, com.hbase.protoc.TemporalAgg.TemporalAggResponse.Builder.class);
      }

      // Construct using com.hbase.protoc.TemporalAgg.TemporalAggResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTimeMapFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (timeMapBuilder_ == null) {
          timeMap_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          timeMapBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hbase.protoc.TemporalAgg.internal_static_TemporalAggResponse_descriptor;
      }

      public com.hbase.protoc.TemporalAgg.TemporalAggResponse getDefaultInstanceForType() {
        return com.hbase.protoc.TemporalAgg.TemporalAggResponse.getDefaultInstance();
      }

      public com.hbase.protoc.TemporalAgg.TemporalAggResponse build() {
        com.hbase.protoc.TemporalAgg.TemporalAggResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hbase.protoc.TemporalAgg.TemporalAggResponse buildPartial() {
        com.hbase.protoc.TemporalAgg.TemporalAggResponse result = new com.hbase.protoc.TemporalAgg.TemporalAggResponse(this);
        int from_bitField0_ = bitField0_;
        if (timeMapBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            timeMap_ = java.util.Collections.unmodifiableList(timeMap_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.timeMap_ = timeMap_;
        } else {
          result.timeMap_ = timeMapBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hbase.protoc.TemporalAgg.TemporalAggResponse) {
          return mergeFrom((com.hbase.protoc.TemporalAgg.TemporalAggResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hbase.protoc.TemporalAgg.TemporalAggResponse other) {
        if (other == com.hbase.protoc.TemporalAgg.TemporalAggResponse.getDefaultInstance()) return this;
        if (timeMapBuilder_ == null) {
          if (!other.timeMap_.isEmpty()) {
            if (timeMap_.isEmpty()) {
              timeMap_ = other.timeMap_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTimeMapIsMutable();
              timeMap_.addAll(other.timeMap_);
            }
            onChanged();
          }
        } else {
          if (!other.timeMap_.isEmpty()) {
            if (timeMapBuilder_.isEmpty()) {
              timeMapBuilder_.dispose();
              timeMapBuilder_ = null;
              timeMap_ = other.timeMap_;
              bitField0_ = (bitField0_ & ~0x00000001);
              timeMapBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTimeMapFieldBuilder() : null;
            } else {
              timeMapBuilder_.addAllMessages(other.timeMap_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hbase.protoc.TemporalAgg.TemporalAggResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hbase.protoc.TemporalAgg.TemporalAggResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .TemporalAggResponse.TimeMap timeMap = 1;
      private java.util.List<com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap> timeMap_ =
        java.util.Collections.emptyList();
      private void ensureTimeMapIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          timeMap_ = new java.util.ArrayList<com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap>(timeMap_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap, com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap.Builder, com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMapOrBuilder> timeMapBuilder_;

      /**
       * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
       */
      public java.util.List<com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap> getTimeMapList() {
        if (timeMapBuilder_ == null) {
          return java.util.Collections.unmodifiableList(timeMap_);
        } else {
          return timeMapBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
       */
      public int getTimeMapCount() {
        if (timeMapBuilder_ == null) {
          return timeMap_.size();
        } else {
          return timeMapBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
       */
      public com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap getTimeMap(int index) {
        if (timeMapBuilder_ == null) {
          return timeMap_.get(index);
        } else {
          return timeMapBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
       */
      public Builder setTimeMap(
          int index, com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap value) {
        if (timeMapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimeMapIsMutable();
          timeMap_.set(index, value);
          onChanged();
        } else {
          timeMapBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
       */
      public Builder setTimeMap(
          int index, com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap.Builder builderForValue) {
        if (timeMapBuilder_ == null) {
          ensureTimeMapIsMutable();
          timeMap_.set(index, builderForValue.build());
          onChanged();
        } else {
          timeMapBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
       */
      public Builder addTimeMap(com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap value) {
        if (timeMapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimeMapIsMutable();
          timeMap_.add(value);
          onChanged();
        } else {
          timeMapBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
       */
      public Builder addTimeMap(
          int index, com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap value) {
        if (timeMapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimeMapIsMutable();
          timeMap_.add(index, value);
          onChanged();
        } else {
          timeMapBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
       */
      public Builder addTimeMap(
          com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap.Builder builderForValue) {
        if (timeMapBuilder_ == null) {
          ensureTimeMapIsMutable();
          timeMap_.add(builderForValue.build());
          onChanged();
        } else {
          timeMapBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
       */
      public Builder addTimeMap(
          int index, com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap.Builder builderForValue) {
        if (timeMapBuilder_ == null) {
          ensureTimeMapIsMutable();
          timeMap_.add(index, builderForValue.build());
          onChanged();
        } else {
          timeMapBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
       */
      public Builder addAllTimeMap(
          java.lang.Iterable<? extends com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap> values) {
        if (timeMapBuilder_ == null) {
          ensureTimeMapIsMutable();
          super.addAll(values, timeMap_);
          onChanged();
        } else {
          timeMapBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
       */
      public Builder clearTimeMap() {
        if (timeMapBuilder_ == null) {
          timeMap_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          timeMapBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
       */
      public Builder removeTimeMap(int index) {
        if (timeMapBuilder_ == null) {
          ensureTimeMapIsMutable();
          timeMap_.remove(index);
          onChanged();
        } else {
          timeMapBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
       */
      public com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap.Builder getTimeMapBuilder(
          int index) {
        return getTimeMapFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
       */
      public com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMapOrBuilder getTimeMapOrBuilder(
          int index) {
        if (timeMapBuilder_ == null) {
          return timeMap_.get(index);  } else {
          return timeMapBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
       */
      public java.util.List<? extends com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMapOrBuilder> 
           getTimeMapOrBuilderList() {
        if (timeMapBuilder_ != null) {
          return timeMapBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(timeMap_);
        }
      }
      /**
       * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
       */
      public com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap.Builder addTimeMapBuilder() {
        return getTimeMapFieldBuilder().addBuilder(
            com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap.getDefaultInstance());
      }
      /**
       * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
       */
      public com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap.Builder addTimeMapBuilder(
          int index) {
        return getTimeMapFieldBuilder().addBuilder(
            index, com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap.getDefaultInstance());
      }
      /**
       * <code>repeated .TemporalAggResponse.TimeMap timeMap = 1;</code>
       */
      public java.util.List<com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap.Builder> 
           getTimeMapBuilderList() {
        return getTimeMapFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap, com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap.Builder, com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMapOrBuilder> 
          getTimeMapFieldBuilder() {
        if (timeMapBuilder_ == null) {
          timeMapBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap, com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMap.Builder, com.hbase.protoc.TemporalAgg.TemporalAggResponse.TimeMapOrBuilder>(
                  timeMap_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          timeMap_ = null;
        }
        return timeMapBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:TemporalAggResponse)
    }

    static {
      defaultInstance = new TemporalAggResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:TemporalAggResponse)
  }

  /**
   * Protobuf service {@code TemporalAggService}
   */
  public static abstract class TemporalAggService
      implements com.google.protobuf.Service {
    protected TemporalAggService() {}

    public interface Interface {
      /**
       * <code>rpc getTemporalAgg(.TemporalAggRequest) returns (.TemporalAggResponse);</code>
       */
      public abstract void getTemporalAgg(
          com.google.protobuf.RpcController controller,
          com.hbase.protoc.TemporalAgg.TemporalAggRequest request,
          com.google.protobuf.RpcCallback<com.hbase.protoc.TemporalAgg.TemporalAggResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new TemporalAggService() {
        @java.lang.Override
        public  void getTemporalAgg(
            com.google.protobuf.RpcController controller,
            com.hbase.protoc.TemporalAgg.TemporalAggRequest request,
            com.google.protobuf.RpcCallback<com.hbase.protoc.TemporalAgg.TemporalAggResponse> done) {
          impl.getTemporalAgg(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getTemporalAgg(controller, (com.hbase.protoc.TemporalAgg.TemporalAggRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.hbase.protoc.TemporalAgg.TemporalAggRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.hbase.protoc.TemporalAgg.TemporalAggResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc getTemporalAgg(.TemporalAggRequest) returns (.TemporalAggResponse);</code>
     */
    public abstract void getTemporalAgg(
        com.google.protobuf.RpcController controller,
        com.hbase.protoc.TemporalAgg.TemporalAggRequest request,
        com.google.protobuf.RpcCallback<com.hbase.protoc.TemporalAgg.TemporalAggResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.hbase.protoc.TemporalAgg.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getTemporalAgg(controller, (com.hbase.protoc.TemporalAgg.TemporalAggRequest)request,
            com.google.protobuf.RpcUtil.<com.hbase.protoc.TemporalAgg.TemporalAggResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.hbase.protoc.TemporalAgg.TemporalAggRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.hbase.protoc.TemporalAgg.TemporalAggResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.hbase.protoc.TemporalAgg.TemporalAggService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getTemporalAgg(
          com.google.protobuf.RpcController controller,
          com.hbase.protoc.TemporalAgg.TemporalAggRequest request,
          com.google.protobuf.RpcCallback<com.hbase.protoc.TemporalAgg.TemporalAggResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.hbase.protoc.TemporalAgg.TemporalAggResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.hbase.protoc.TemporalAgg.TemporalAggResponse.class,
            com.hbase.protoc.TemporalAgg.TemporalAggResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.hbase.protoc.TemporalAgg.TemporalAggResponse getTemporalAgg(
          com.google.protobuf.RpcController controller,
          com.hbase.protoc.TemporalAgg.TemporalAggRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.hbase.protoc.TemporalAgg.TemporalAggResponse getTemporalAgg(
          com.google.protobuf.RpcController controller,
          com.hbase.protoc.TemporalAgg.TemporalAggRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.hbase.protoc.TemporalAgg.TemporalAggResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.hbase.protoc.TemporalAgg.TemporalAggResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:TemporalAggService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TemporalAggRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TemporalAggRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TemporalAggResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TemporalAggResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TemporalAggResponse_TimeMap_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TemporalAggResponse_TimeMap_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022temporalAgg.protoc\"Z\n\022TemporalAggReque" +
      "st\022\016\n\006rowkey\030\001 \002(\t\022\020\n\010cateList\030\002 \002(\t\022\021\n\t" +
      "startTime\030\003 \002(\t\022\017\n\007endTime\030\004 \002(\t\"k\n\023Temp" +
      "oralAggResponse\022-\n\007timeMap\030\001 \003(\0132\034.Tempo" +
      "ralAggResponse.TimeMap\032%\n\007TimeMap\022\013\n\003key" +
      "\030\001 \001(\t\022\r\n\005value\030\002 \001(\0032Q\n\022TemporalAggServ" +
      "ice\022;\n\016getTemporalAgg\022\023.TemporalAggReque" +
      "st\032\024.TemporalAggResponseB\'\n\020com.hbase.pr" +
      "otocB\013TemporalAggH\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_TemporalAggRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_TemporalAggRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TemporalAggRequest_descriptor,
              new java.lang.String[] { "Rowkey", "CateList", "StartTime", "EndTime", });
          internal_static_TemporalAggResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_TemporalAggResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TemporalAggResponse_descriptor,
              new java.lang.String[] { "TimeMap", });
          internal_static_TemporalAggResponse_TimeMap_descriptor =
            internal_static_TemporalAggResponse_descriptor.getNestedTypes().get(0);
          internal_static_TemporalAggResponse_TimeMap_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TemporalAggResponse_TimeMap_descriptor,
              new java.lang.String[] { "Key", "Value", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
