// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/com/hbase/protoc/matriagg.protoc

package com.hbase.protoc;

public final class MatrixColAgg {
  private MatrixColAgg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MatrixColAggRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string startKey = 1;
    /**
     * <code>optional string startKey = 1;</code>
     */
    boolean hasStartKey();
    /**
     * <code>optional string startKey = 1;</code>
     */
    java.lang.String getStartKey();
    /**
     * <code>optional string startKey = 1;</code>
     */
    com.google.protobuf.ByteString
        getStartKeyBytes();

    // optional string endKey = 2;
    /**
     * <code>optional string endKey = 2;</code>
     */
    boolean hasEndKey();
    /**
     * <code>optional string endKey = 2;</code>
     */
    java.lang.String getEndKey();
    /**
     * <code>optional string endKey = 2;</code>
     */
    com.google.protobuf.ByteString
        getEndKeyBytes();
  }
  /**
   * Protobuf type {@code MatrixColAggRequest}
   */
  public static final class MatrixColAggRequest extends
      com.google.protobuf.GeneratedMessage
      implements MatrixColAggRequestOrBuilder {
    // Use MatrixColAggRequest.newBuilder() to construct.
    private MatrixColAggRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MatrixColAggRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MatrixColAggRequest defaultInstance;
    public static MatrixColAggRequest getDefaultInstance() {
      return defaultInstance;
    }

    public MatrixColAggRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MatrixColAggRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              startKey_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              endKey_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hbase.protoc.MatrixColAgg.internal_static_MatrixColAggRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hbase.protoc.MatrixColAgg.internal_static_MatrixColAggRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hbase.protoc.MatrixColAgg.MatrixColAggRequest.class, com.hbase.protoc.MatrixColAgg.MatrixColAggRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<MatrixColAggRequest> PARSER =
        new com.google.protobuf.AbstractParser<MatrixColAggRequest>() {
      public MatrixColAggRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MatrixColAggRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MatrixColAggRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string startKey = 1;
    public static final int STARTKEY_FIELD_NUMBER = 1;
    private java.lang.Object startKey_;
    /**
     * <code>optional string startKey = 1;</code>
     */
    public boolean hasStartKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string startKey = 1;</code>
     */
    public java.lang.String getStartKey() {
      java.lang.Object ref = startKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          startKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string startKey = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStartKeyBytes() {
      java.lang.Object ref = startKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string endKey = 2;
    public static final int ENDKEY_FIELD_NUMBER = 2;
    private java.lang.Object endKey_;
    /**
     * <code>optional string endKey = 2;</code>
     */
    public boolean hasEndKey() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string endKey = 2;</code>
     */
    public java.lang.String getEndKey() {
      java.lang.Object ref = endKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          endKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string endKey = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEndKeyBytes() {
      java.lang.Object ref = endKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      startKey_ = "";
      endKey_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStartKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getEndKeyBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStartKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getEndKeyBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hbase.protoc.MatrixColAgg.MatrixColAggRequest)) {
        return super.equals(obj);
      }
      com.hbase.protoc.MatrixColAgg.MatrixColAggRequest other = (com.hbase.protoc.MatrixColAgg.MatrixColAggRequest) obj;

      boolean result = true;
      result = result && (hasStartKey() == other.hasStartKey());
      if (hasStartKey()) {
        result = result && getStartKey()
            .equals(other.getStartKey());
      }
      result = result && (hasEndKey() == other.hasEndKey());
      if (hasEndKey()) {
        result = result && getEndKey()
            .equals(other.getEndKey());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasStartKey()) {
        hash = (37 * hash) + STARTKEY_FIELD_NUMBER;
        hash = (53 * hash) + getStartKey().hashCode();
      }
      if (hasEndKey()) {
        hash = (37 * hash) + ENDKEY_FIELD_NUMBER;
        hash = (53 * hash) + getEndKey().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hbase.protoc.MatrixColAgg.MatrixColAggRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.protoc.MatrixColAgg.MatrixColAggRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.protoc.MatrixColAgg.MatrixColAggRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.protoc.MatrixColAgg.MatrixColAggRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.protoc.MatrixColAgg.MatrixColAggRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.protoc.MatrixColAgg.MatrixColAggRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hbase.protoc.MatrixColAgg.MatrixColAggRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hbase.protoc.MatrixColAgg.MatrixColAggRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hbase.protoc.MatrixColAgg.MatrixColAggRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.protoc.MatrixColAgg.MatrixColAggRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hbase.protoc.MatrixColAgg.MatrixColAggRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MatrixColAggRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hbase.protoc.MatrixColAgg.MatrixColAggRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hbase.protoc.MatrixColAgg.internal_static_MatrixColAggRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hbase.protoc.MatrixColAgg.internal_static_MatrixColAggRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hbase.protoc.MatrixColAgg.MatrixColAggRequest.class, com.hbase.protoc.MatrixColAgg.MatrixColAggRequest.Builder.class);
      }

      // Construct using com.hbase.protoc.MatrixColAgg.MatrixColAggRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        startKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        endKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hbase.protoc.MatrixColAgg.internal_static_MatrixColAggRequest_descriptor;
      }

      public com.hbase.protoc.MatrixColAgg.MatrixColAggRequest getDefaultInstanceForType() {
        return com.hbase.protoc.MatrixColAgg.MatrixColAggRequest.getDefaultInstance();
      }

      public com.hbase.protoc.MatrixColAgg.MatrixColAggRequest build() {
        com.hbase.protoc.MatrixColAgg.MatrixColAggRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hbase.protoc.MatrixColAgg.MatrixColAggRequest buildPartial() {
        com.hbase.protoc.MatrixColAgg.MatrixColAggRequest result = new com.hbase.protoc.MatrixColAgg.MatrixColAggRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.startKey_ = startKey_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.endKey_ = endKey_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hbase.protoc.MatrixColAgg.MatrixColAggRequest) {
          return mergeFrom((com.hbase.protoc.MatrixColAgg.MatrixColAggRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hbase.protoc.MatrixColAgg.MatrixColAggRequest other) {
        if (other == com.hbase.protoc.MatrixColAgg.MatrixColAggRequest.getDefaultInstance()) return this;
        if (other.hasStartKey()) {
          bitField0_ |= 0x00000001;
          startKey_ = other.startKey_;
          onChanged();
        }
        if (other.hasEndKey()) {
          bitField0_ |= 0x00000002;
          endKey_ = other.endKey_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hbase.protoc.MatrixColAgg.MatrixColAggRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hbase.protoc.MatrixColAgg.MatrixColAggRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string startKey = 1;
      private java.lang.Object startKey_ = "";
      /**
       * <code>optional string startKey = 1;</code>
       */
      public boolean hasStartKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string startKey = 1;</code>
       */
      public java.lang.String getStartKey() {
        java.lang.Object ref = startKey_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          startKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string startKey = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStartKeyBytes() {
        java.lang.Object ref = startKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          startKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string startKey = 1;</code>
       */
      public Builder setStartKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        startKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string startKey = 1;</code>
       */
      public Builder clearStartKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        startKey_ = getDefaultInstance().getStartKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string startKey = 1;</code>
       */
      public Builder setStartKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        startKey_ = value;
        onChanged();
        return this;
      }

      // optional string endKey = 2;
      private java.lang.Object endKey_ = "";
      /**
       * <code>optional string endKey = 2;</code>
       */
      public boolean hasEndKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string endKey = 2;</code>
       */
      public java.lang.String getEndKey() {
        java.lang.Object ref = endKey_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          endKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string endKey = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEndKeyBytes() {
        java.lang.Object ref = endKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          endKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string endKey = 2;</code>
       */
      public Builder setEndKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        endKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string endKey = 2;</code>
       */
      public Builder clearEndKey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        endKey_ = getDefaultInstance().getEndKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string endKey = 2;</code>
       */
      public Builder setEndKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        endKey_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MatrixColAggRequest)
    }

    static {
      defaultInstance = new MatrixColAggRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MatrixColAggRequest)
  }

  public interface MatrixColAggResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .SumMatrix sum = 1;
    /**
     * <code>repeated .SumMatrix sum = 1;</code>
     */
    java.util.List<com.hbase.protoc.MatrixColAgg.SumMatrix> 
        getSumList();
    /**
     * <code>repeated .SumMatrix sum = 1;</code>
     */
    com.hbase.protoc.MatrixColAgg.SumMatrix getSum(int index);
    /**
     * <code>repeated .SumMatrix sum = 1;</code>
     */
    int getSumCount();
    /**
     * <code>repeated .SumMatrix sum = 1;</code>
     */
    java.util.List<? extends com.hbase.protoc.MatrixColAgg.SumMatrixOrBuilder> 
        getSumOrBuilderList();
    /**
     * <code>repeated .SumMatrix sum = 1;</code>
     */
    com.hbase.protoc.MatrixColAgg.SumMatrixOrBuilder getSumOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code MatrixColAggResponse}
   */
  public static final class MatrixColAggResponse extends
      com.google.protobuf.GeneratedMessage
      implements MatrixColAggResponseOrBuilder {
    // Use MatrixColAggResponse.newBuilder() to construct.
    private MatrixColAggResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MatrixColAggResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MatrixColAggResponse defaultInstance;
    public static MatrixColAggResponse getDefaultInstance() {
      return defaultInstance;
    }

    public MatrixColAggResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MatrixColAggResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                sum_ = new java.util.ArrayList<com.hbase.protoc.MatrixColAgg.SumMatrix>();
                mutable_bitField0_ |= 0x00000001;
              }
              sum_.add(input.readMessage(com.hbase.protoc.MatrixColAgg.SumMatrix.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          sum_ = java.util.Collections.unmodifiableList(sum_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hbase.protoc.MatrixColAgg.internal_static_MatrixColAggResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hbase.protoc.MatrixColAgg.internal_static_MatrixColAggResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hbase.protoc.MatrixColAgg.MatrixColAggResponse.class, com.hbase.protoc.MatrixColAgg.MatrixColAggResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<MatrixColAggResponse> PARSER =
        new com.google.protobuf.AbstractParser<MatrixColAggResponse>() {
      public MatrixColAggResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MatrixColAggResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MatrixColAggResponse> getParserForType() {
      return PARSER;
    }

    // repeated .SumMatrix sum = 1;
    public static final int SUM_FIELD_NUMBER = 1;
    private java.util.List<com.hbase.protoc.MatrixColAgg.SumMatrix> sum_;
    /**
     * <code>repeated .SumMatrix sum = 1;</code>
     */
    public java.util.List<com.hbase.protoc.MatrixColAgg.SumMatrix> getSumList() {
      return sum_;
    }
    /**
     * <code>repeated .SumMatrix sum = 1;</code>
     */
    public java.util.List<? extends com.hbase.protoc.MatrixColAgg.SumMatrixOrBuilder> 
        getSumOrBuilderList() {
      return sum_;
    }
    /**
     * <code>repeated .SumMatrix sum = 1;</code>
     */
    public int getSumCount() {
      return sum_.size();
    }
    /**
     * <code>repeated .SumMatrix sum = 1;</code>
     */
    public com.hbase.protoc.MatrixColAgg.SumMatrix getSum(int index) {
      return sum_.get(index);
    }
    /**
     * <code>repeated .SumMatrix sum = 1;</code>
     */
    public com.hbase.protoc.MatrixColAgg.SumMatrixOrBuilder getSumOrBuilder(
        int index) {
      return sum_.get(index);
    }

    private void initFields() {
      sum_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < sum_.size(); i++) {
        output.writeMessage(1, sum_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < sum_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sum_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hbase.protoc.MatrixColAgg.MatrixColAggResponse)) {
        return super.equals(obj);
      }
      com.hbase.protoc.MatrixColAgg.MatrixColAggResponse other = (com.hbase.protoc.MatrixColAgg.MatrixColAggResponse) obj;

      boolean result = true;
      result = result && getSumList()
          .equals(other.getSumList());
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getSumCount() > 0) {
        hash = (37 * hash) + SUM_FIELD_NUMBER;
        hash = (53 * hash) + getSumList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hbase.protoc.MatrixColAgg.MatrixColAggResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.protoc.MatrixColAgg.MatrixColAggResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.protoc.MatrixColAgg.MatrixColAggResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.protoc.MatrixColAgg.MatrixColAggResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.protoc.MatrixColAgg.MatrixColAggResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.protoc.MatrixColAgg.MatrixColAggResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hbase.protoc.MatrixColAgg.MatrixColAggResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hbase.protoc.MatrixColAgg.MatrixColAggResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hbase.protoc.MatrixColAgg.MatrixColAggResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.protoc.MatrixColAgg.MatrixColAggResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hbase.protoc.MatrixColAgg.MatrixColAggResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MatrixColAggResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hbase.protoc.MatrixColAgg.MatrixColAggResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hbase.protoc.MatrixColAgg.internal_static_MatrixColAggResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hbase.protoc.MatrixColAgg.internal_static_MatrixColAggResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hbase.protoc.MatrixColAgg.MatrixColAggResponse.class, com.hbase.protoc.MatrixColAgg.MatrixColAggResponse.Builder.class);
      }

      // Construct using com.hbase.protoc.MatrixColAgg.MatrixColAggResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSumFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (sumBuilder_ == null) {
          sum_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          sumBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hbase.protoc.MatrixColAgg.internal_static_MatrixColAggResponse_descriptor;
      }

      public com.hbase.protoc.MatrixColAgg.MatrixColAggResponse getDefaultInstanceForType() {
        return com.hbase.protoc.MatrixColAgg.MatrixColAggResponse.getDefaultInstance();
      }

      public com.hbase.protoc.MatrixColAgg.MatrixColAggResponse build() {
        com.hbase.protoc.MatrixColAgg.MatrixColAggResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hbase.protoc.MatrixColAgg.MatrixColAggResponse buildPartial() {
        com.hbase.protoc.MatrixColAgg.MatrixColAggResponse result = new com.hbase.protoc.MatrixColAgg.MatrixColAggResponse(this);
        int from_bitField0_ = bitField0_;
        if (sumBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            sum_ = java.util.Collections.unmodifiableList(sum_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.sum_ = sum_;
        } else {
          result.sum_ = sumBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hbase.protoc.MatrixColAgg.MatrixColAggResponse) {
          return mergeFrom((com.hbase.protoc.MatrixColAgg.MatrixColAggResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hbase.protoc.MatrixColAgg.MatrixColAggResponse other) {
        if (other == com.hbase.protoc.MatrixColAgg.MatrixColAggResponse.getDefaultInstance()) return this;
        if (sumBuilder_ == null) {
          if (!other.sum_.isEmpty()) {
            if (sum_.isEmpty()) {
              sum_ = other.sum_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSumIsMutable();
              sum_.addAll(other.sum_);
            }
            onChanged();
          }
        } else {
          if (!other.sum_.isEmpty()) {
            if (sumBuilder_.isEmpty()) {
              sumBuilder_.dispose();
              sumBuilder_ = null;
              sum_ = other.sum_;
              bitField0_ = (bitField0_ & ~0x00000001);
              sumBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSumFieldBuilder() : null;
            } else {
              sumBuilder_.addAllMessages(other.sum_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hbase.protoc.MatrixColAgg.MatrixColAggResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hbase.protoc.MatrixColAgg.MatrixColAggResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .SumMatrix sum = 1;
      private java.util.List<com.hbase.protoc.MatrixColAgg.SumMatrix> sum_ =
        java.util.Collections.emptyList();
      private void ensureSumIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          sum_ = new java.util.ArrayList<com.hbase.protoc.MatrixColAgg.SumMatrix>(sum_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.hbase.protoc.MatrixColAgg.SumMatrix, com.hbase.protoc.MatrixColAgg.SumMatrix.Builder, com.hbase.protoc.MatrixColAgg.SumMatrixOrBuilder> sumBuilder_;

      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public java.util.List<com.hbase.protoc.MatrixColAgg.SumMatrix> getSumList() {
        if (sumBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sum_);
        } else {
          return sumBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public int getSumCount() {
        if (sumBuilder_ == null) {
          return sum_.size();
        } else {
          return sumBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public com.hbase.protoc.MatrixColAgg.SumMatrix getSum(int index) {
        if (sumBuilder_ == null) {
          return sum_.get(index);
        } else {
          return sumBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public Builder setSum(
          int index, com.hbase.protoc.MatrixColAgg.SumMatrix value) {
        if (sumBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSumIsMutable();
          sum_.set(index, value);
          onChanged();
        } else {
          sumBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public Builder setSum(
          int index, com.hbase.protoc.MatrixColAgg.SumMatrix.Builder builderForValue) {
        if (sumBuilder_ == null) {
          ensureSumIsMutable();
          sum_.set(index, builderForValue.build());
          onChanged();
        } else {
          sumBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public Builder addSum(com.hbase.protoc.MatrixColAgg.SumMatrix value) {
        if (sumBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSumIsMutable();
          sum_.add(value);
          onChanged();
        } else {
          sumBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public Builder addSum(
          int index, com.hbase.protoc.MatrixColAgg.SumMatrix value) {
        if (sumBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSumIsMutable();
          sum_.add(index, value);
          onChanged();
        } else {
          sumBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public Builder addSum(
          com.hbase.protoc.MatrixColAgg.SumMatrix.Builder builderForValue) {
        if (sumBuilder_ == null) {
          ensureSumIsMutable();
          sum_.add(builderForValue.build());
          onChanged();
        } else {
          sumBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public Builder addSum(
          int index, com.hbase.protoc.MatrixColAgg.SumMatrix.Builder builderForValue) {
        if (sumBuilder_ == null) {
          ensureSumIsMutable();
          sum_.add(index, builderForValue.build());
          onChanged();
        } else {
          sumBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public Builder addAllSum(
          java.lang.Iterable<? extends com.hbase.protoc.MatrixColAgg.SumMatrix> values) {
        if (sumBuilder_ == null) {
          ensureSumIsMutable();
          super.addAll(values, sum_);
          onChanged();
        } else {
          sumBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public Builder clearSum() {
        if (sumBuilder_ == null) {
          sum_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          sumBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public Builder removeSum(int index) {
        if (sumBuilder_ == null) {
          ensureSumIsMutable();
          sum_.remove(index);
          onChanged();
        } else {
          sumBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public com.hbase.protoc.MatrixColAgg.SumMatrix.Builder getSumBuilder(
          int index) {
        return getSumFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public com.hbase.protoc.MatrixColAgg.SumMatrixOrBuilder getSumOrBuilder(
          int index) {
        if (sumBuilder_ == null) {
          return sum_.get(index);  } else {
          return sumBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public java.util.List<? extends com.hbase.protoc.MatrixColAgg.SumMatrixOrBuilder> 
           getSumOrBuilderList() {
        if (sumBuilder_ != null) {
          return sumBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sum_);
        }
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public com.hbase.protoc.MatrixColAgg.SumMatrix.Builder addSumBuilder() {
        return getSumFieldBuilder().addBuilder(
            com.hbase.protoc.MatrixColAgg.SumMatrix.getDefaultInstance());
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public com.hbase.protoc.MatrixColAgg.SumMatrix.Builder addSumBuilder(
          int index) {
        return getSumFieldBuilder().addBuilder(
            index, com.hbase.protoc.MatrixColAgg.SumMatrix.getDefaultInstance());
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public java.util.List<com.hbase.protoc.MatrixColAgg.SumMatrix.Builder> 
           getSumBuilderList() {
        return getSumFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.hbase.protoc.MatrixColAgg.SumMatrix, com.hbase.protoc.MatrixColAgg.SumMatrix.Builder, com.hbase.protoc.MatrixColAgg.SumMatrixOrBuilder> 
          getSumFieldBuilder() {
        if (sumBuilder_ == null) {
          sumBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.hbase.protoc.MatrixColAgg.SumMatrix, com.hbase.protoc.MatrixColAgg.SumMatrix.Builder, com.hbase.protoc.MatrixColAgg.SumMatrixOrBuilder>(
                  sum_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          sum_ = null;
        }
        return sumBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:MatrixColAggResponse)
    }

    static {
      defaultInstance = new MatrixColAggResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MatrixColAggResponse)
  }

  public interface SumMatrixOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated int32 array = 1;
    /**
     * <code>repeated int32 array = 1;</code>
     */
    java.util.List<java.lang.Integer> getArrayList();
    /**
     * <code>repeated int32 array = 1;</code>
     */
    int getArrayCount();
    /**
     * <code>repeated int32 array = 1;</code>
     */
    int getArray(int index);
  }
  /**
   * Protobuf type {@code SumMatrix}
   */
  public static final class SumMatrix extends
      com.google.protobuf.GeneratedMessage
      implements SumMatrixOrBuilder {
    // Use SumMatrix.newBuilder() to construct.
    private SumMatrix(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SumMatrix(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SumMatrix defaultInstance;
    public static SumMatrix getDefaultInstance() {
      return defaultInstance;
    }

    public SumMatrix getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SumMatrix(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                array_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              array_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                array_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                array_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          array_ = java.util.Collections.unmodifiableList(array_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hbase.protoc.MatrixColAgg.internal_static_SumMatrix_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hbase.protoc.MatrixColAgg.internal_static_SumMatrix_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hbase.protoc.MatrixColAgg.SumMatrix.class, com.hbase.protoc.MatrixColAgg.SumMatrix.Builder.class);
    }

    public static com.google.protobuf.Parser<SumMatrix> PARSER =
        new com.google.protobuf.AbstractParser<SumMatrix>() {
      public SumMatrix parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SumMatrix(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SumMatrix> getParserForType() {
      return PARSER;
    }

    // repeated int32 array = 1;
    public static final int ARRAY_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> array_;
    /**
     * <code>repeated int32 array = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getArrayList() {
      return array_;
    }
    /**
     * <code>repeated int32 array = 1;</code>
     */
    public int getArrayCount() {
      return array_.size();
    }
    /**
     * <code>repeated int32 array = 1;</code>
     */
    public int getArray(int index) {
      return array_.get(index);
    }

    private void initFields() {
      array_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < array_.size(); i++) {
        output.writeInt32(1, array_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < array_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(array_.get(i));
        }
        size += dataSize;
        size += 1 * getArrayList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hbase.protoc.MatrixColAgg.SumMatrix)) {
        return super.equals(obj);
      }
      com.hbase.protoc.MatrixColAgg.SumMatrix other = (com.hbase.protoc.MatrixColAgg.SumMatrix) obj;

      boolean result = true;
      result = result && getArrayList()
          .equals(other.getArrayList());
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getArrayCount() > 0) {
        hash = (37 * hash) + ARRAY_FIELD_NUMBER;
        hash = (53 * hash) + getArrayList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hbase.protoc.MatrixColAgg.SumMatrix parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.protoc.MatrixColAgg.SumMatrix parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.protoc.MatrixColAgg.SumMatrix parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.protoc.MatrixColAgg.SumMatrix parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.protoc.MatrixColAgg.SumMatrix parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.protoc.MatrixColAgg.SumMatrix parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hbase.protoc.MatrixColAgg.SumMatrix parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hbase.protoc.MatrixColAgg.SumMatrix parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hbase.protoc.MatrixColAgg.SumMatrix parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.protoc.MatrixColAgg.SumMatrix parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hbase.protoc.MatrixColAgg.SumMatrix prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SumMatrix}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hbase.protoc.MatrixColAgg.SumMatrixOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hbase.protoc.MatrixColAgg.internal_static_SumMatrix_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hbase.protoc.MatrixColAgg.internal_static_SumMatrix_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hbase.protoc.MatrixColAgg.SumMatrix.class, com.hbase.protoc.MatrixColAgg.SumMatrix.Builder.class);
      }

      // Construct using com.hbase.protoc.MatrixColAgg.SumMatrix.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        array_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hbase.protoc.MatrixColAgg.internal_static_SumMatrix_descriptor;
      }

      public com.hbase.protoc.MatrixColAgg.SumMatrix getDefaultInstanceForType() {
        return com.hbase.protoc.MatrixColAgg.SumMatrix.getDefaultInstance();
      }

      public com.hbase.protoc.MatrixColAgg.SumMatrix build() {
        com.hbase.protoc.MatrixColAgg.SumMatrix result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hbase.protoc.MatrixColAgg.SumMatrix buildPartial() {
        com.hbase.protoc.MatrixColAgg.SumMatrix result = new com.hbase.protoc.MatrixColAgg.SumMatrix(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          array_ = java.util.Collections.unmodifiableList(array_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.array_ = array_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hbase.protoc.MatrixColAgg.SumMatrix) {
          return mergeFrom((com.hbase.protoc.MatrixColAgg.SumMatrix)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hbase.protoc.MatrixColAgg.SumMatrix other) {
        if (other == com.hbase.protoc.MatrixColAgg.SumMatrix.getDefaultInstance()) return this;
        if (!other.array_.isEmpty()) {
          if (array_.isEmpty()) {
            array_ = other.array_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureArrayIsMutable();
            array_.addAll(other.array_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hbase.protoc.MatrixColAgg.SumMatrix parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hbase.protoc.MatrixColAgg.SumMatrix) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated int32 array = 1;
      private java.util.List<java.lang.Integer> array_ = java.util.Collections.emptyList();
      private void ensureArrayIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          array_ = new java.util.ArrayList<java.lang.Integer>(array_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 array = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getArrayList() {
        return java.util.Collections.unmodifiableList(array_);
      }
      /**
       * <code>repeated int32 array = 1;</code>
       */
      public int getArrayCount() {
        return array_.size();
      }
      /**
       * <code>repeated int32 array = 1;</code>
       */
      public int getArray(int index) {
        return array_.get(index);
      }
      /**
       * <code>repeated int32 array = 1;</code>
       */
      public Builder setArray(
          int index, int value) {
        ensureArrayIsMutable();
        array_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 array = 1;</code>
       */
      public Builder addArray(int value) {
        ensureArrayIsMutable();
        array_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 array = 1;</code>
       */
      public Builder addAllArray(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureArrayIsMutable();
        super.addAll(values, array_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 array = 1;</code>
       */
      public Builder clearArray() {
        array_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SumMatrix)
    }

    static {
      defaultInstance = new SumMatrix(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SumMatrix)
  }

  /**
   * Protobuf service {@code MatrixColAggService}
   */
  public static abstract class MatrixColAggService
      implements com.google.protobuf.Service {
    protected MatrixColAggService() {}

    public interface Interface {
      /**
       * <code>rpc getMatrixColAgg(.MatrixColAggRequest) returns (.MatrixColAggResponse);</code>
       */
      public abstract void getMatrixColAgg(
          com.google.protobuf.RpcController controller,
          com.hbase.protoc.MatrixColAgg.MatrixColAggRequest request,
          com.google.protobuf.RpcCallback<com.hbase.protoc.MatrixColAgg.MatrixColAggResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new MatrixColAggService() {
        @java.lang.Override
        public  void getMatrixColAgg(
            com.google.protobuf.RpcController controller,
            com.hbase.protoc.MatrixColAgg.MatrixColAggRequest request,
            com.google.protobuf.RpcCallback<com.hbase.protoc.MatrixColAgg.MatrixColAggResponse> done) {
          impl.getMatrixColAgg(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getMatrixColAgg(controller, (com.hbase.protoc.MatrixColAgg.MatrixColAggRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.hbase.protoc.MatrixColAgg.MatrixColAggRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.hbase.protoc.MatrixColAgg.MatrixColAggResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc getMatrixColAgg(.MatrixColAggRequest) returns (.MatrixColAggResponse);</code>
     */
    public abstract void getMatrixColAgg(
        com.google.protobuf.RpcController controller,
        com.hbase.protoc.MatrixColAgg.MatrixColAggRequest request,
        com.google.protobuf.RpcCallback<com.hbase.protoc.MatrixColAgg.MatrixColAggResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.hbase.protoc.MatrixColAgg.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getMatrixColAgg(controller, (com.hbase.protoc.MatrixColAgg.MatrixColAggRequest)request,
            com.google.protobuf.RpcUtil.<com.hbase.protoc.MatrixColAgg.MatrixColAggResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.hbase.protoc.MatrixColAgg.MatrixColAggRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.hbase.protoc.MatrixColAgg.MatrixColAggResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.hbase.protoc.MatrixColAgg.MatrixColAggService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getMatrixColAgg(
          com.google.protobuf.RpcController controller,
          com.hbase.protoc.MatrixColAgg.MatrixColAggRequest request,
          com.google.protobuf.RpcCallback<com.hbase.protoc.MatrixColAgg.MatrixColAggResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.hbase.protoc.MatrixColAgg.MatrixColAggResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.hbase.protoc.MatrixColAgg.MatrixColAggResponse.class,
            com.hbase.protoc.MatrixColAgg.MatrixColAggResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.hbase.protoc.MatrixColAgg.MatrixColAggResponse getMatrixColAgg(
          com.google.protobuf.RpcController controller,
          com.hbase.protoc.MatrixColAgg.MatrixColAggRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.hbase.protoc.MatrixColAgg.MatrixColAggResponse getMatrixColAgg(
          com.google.protobuf.RpcController controller,
          com.hbase.protoc.MatrixColAgg.MatrixColAggRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.hbase.protoc.MatrixColAgg.MatrixColAggResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.hbase.protoc.MatrixColAgg.MatrixColAggResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:MatrixColAggService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MatrixColAggRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MatrixColAggRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MatrixColAggResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MatrixColAggResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SumMatrix_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SumMatrix_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$src/com/hbase/protoc/matriagg.protoc\"7" +
      "\n\023MatrixColAggRequest\022\020\n\010startKey\030\001 \001(\t\022" +
      "\016\n\006endKey\030\002 \001(\t\"/\n\024MatrixColAggResponse\022" +
      "\027\n\003sum\030\001 \003(\0132\n.SumMatrix\"\032\n\tSumMatrix\022\r\n" +
      "\005array\030\001 \003(\0052U\n\023MatrixColAggService\022>\n\017g" +
      "etMatrixColAgg\022\024.MatrixColAggRequest\032\025.M" +
      "atrixColAggResponseB(\n\020com.hbase.protocB" +
      "\014MatrixColAggH\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_MatrixColAggRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_MatrixColAggRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MatrixColAggRequest_descriptor,
              new java.lang.String[] { "StartKey", "EndKey", });
          internal_static_MatrixColAggResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_MatrixColAggResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MatrixColAggResponse_descriptor,
              new java.lang.String[] { "Sum", });
          internal_static_SumMatrix_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_SumMatrix_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SumMatrix_descriptor,
              new java.lang.String[] { "Array", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
