// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spatialAgg.protoc

package com.hbase.protoc;

public final class SpatialAgg {
  private SpatialAgg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SpatialAggRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string startTime = 1;
    /**
     * <code>required string startTime = 1;</code>
     */
    boolean hasStartTime();
    /**
     * <code>required string startTime = 1;</code>
     */
    java.lang.String getStartTime();
    /**
     * <code>required string startTime = 1;</code>
     */
    com.google.protobuf.ByteString
        getStartTimeBytes();

    // required string endTime = 2;
    /**
     * <code>required string endTime = 2;</code>
     */
    boolean hasEndTime();
    /**
     * <code>required string endTime = 2;</code>
     */
    java.lang.String getEndTime();
    /**
     * <code>required string endTime = 2;</code>
     */
    com.google.protobuf.ByteString
        getEndTimeBytes();

    // required string rowKey = 3;
    /**
     * <code>required string rowKey = 3;</code>
     */
    boolean hasRowKey();
    /**
     * <code>required string rowKey = 3;</code>
     */
    java.lang.String getRowKey();
    /**
     * <code>required string rowKey = 3;</code>
     */
    com.google.protobuf.ByteString
        getRowKeyBytes();
  }
  /**
   * Protobuf type {@code SpatialAggRequest}
   */
  public static final class SpatialAggRequest extends
      com.google.protobuf.GeneratedMessage
      implements SpatialAggRequestOrBuilder {
    // Use SpatialAggRequest.newBuilder() to construct.
    private SpatialAggRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SpatialAggRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SpatialAggRequest defaultInstance;
    public static SpatialAggRequest getDefaultInstance() {
      return defaultInstance;
    }

    public SpatialAggRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SpatialAggRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              startTime_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              endTime_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              rowKey_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hbase.protoc.SpatialAgg.internal_static_SpatialAggRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hbase.protoc.SpatialAgg.internal_static_SpatialAggRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hbase.protoc.SpatialAgg.SpatialAggRequest.class, com.hbase.protoc.SpatialAgg.SpatialAggRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<SpatialAggRequest> PARSER =
        new com.google.protobuf.AbstractParser<SpatialAggRequest>() {
      public SpatialAggRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SpatialAggRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SpatialAggRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string startTime = 1;
    public static final int STARTTIME_FIELD_NUMBER = 1;
    private java.lang.Object startTime_;
    /**
     * <code>required string startTime = 1;</code>
     */
    public boolean hasStartTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string startTime = 1;</code>
     */
    public java.lang.String getStartTime() {
      java.lang.Object ref = startTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          startTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string startTime = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStartTimeBytes() {
      java.lang.Object ref = startTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string endTime = 2;
    public static final int ENDTIME_FIELD_NUMBER = 2;
    private java.lang.Object endTime_;
    /**
     * <code>required string endTime = 2;</code>
     */
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string endTime = 2;</code>
     */
    public java.lang.String getEndTime() {
      java.lang.Object ref = endTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          endTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string endTime = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEndTimeBytes() {
      java.lang.Object ref = endTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string rowKey = 3;
    public static final int ROWKEY_FIELD_NUMBER = 3;
    private java.lang.Object rowKey_;
    /**
     * <code>required string rowKey = 3;</code>
     */
    public boolean hasRowKey() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string rowKey = 3;</code>
     */
    public java.lang.String getRowKey() {
      java.lang.Object ref = rowKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          rowKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string rowKey = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRowKeyBytes() {
      java.lang.Object ref = rowKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rowKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      startTime_ = "";
      endTime_ = "";
      rowKey_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStartTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEndTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRowKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStartTimeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getEndTimeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getRowKeyBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStartTimeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getEndTimeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getRowKeyBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hbase.protoc.SpatialAgg.SpatialAggRequest)) {
        return super.equals(obj);
      }
      com.hbase.protoc.SpatialAgg.SpatialAggRequest other = (com.hbase.protoc.SpatialAgg.SpatialAggRequest) obj;

      boolean result = true;
      result = result && (hasStartTime() == other.hasStartTime());
      if (hasStartTime()) {
        result = result && getStartTime()
            .equals(other.getStartTime());
      }
      result = result && (hasEndTime() == other.hasEndTime());
      if (hasEndTime()) {
        result = result && getEndTime()
            .equals(other.getEndTime());
      }
      result = result && (hasRowKey() == other.hasRowKey());
      if (hasRowKey()) {
        result = result && getRowKey()
            .equals(other.getRowKey());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasStartTime()) {
        hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
        hash = (53 * hash) + getStartTime().hashCode();
      }
      if (hasEndTime()) {
        hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
        hash = (53 * hash) + getEndTime().hashCode();
      }
      if (hasRowKey()) {
        hash = (37 * hash) + ROWKEY_FIELD_NUMBER;
        hash = (53 * hash) + getRowKey().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hbase.protoc.SpatialAgg.SpatialAggRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.protoc.SpatialAgg.SpatialAggRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.protoc.SpatialAgg.SpatialAggRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.protoc.SpatialAgg.SpatialAggRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.protoc.SpatialAgg.SpatialAggRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.protoc.SpatialAgg.SpatialAggRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hbase.protoc.SpatialAgg.SpatialAggRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hbase.protoc.SpatialAgg.SpatialAggRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hbase.protoc.SpatialAgg.SpatialAggRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.protoc.SpatialAgg.SpatialAggRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hbase.protoc.SpatialAgg.SpatialAggRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SpatialAggRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hbase.protoc.SpatialAgg.SpatialAggRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hbase.protoc.SpatialAgg.internal_static_SpatialAggRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hbase.protoc.SpatialAgg.internal_static_SpatialAggRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hbase.protoc.SpatialAgg.SpatialAggRequest.class, com.hbase.protoc.SpatialAgg.SpatialAggRequest.Builder.class);
      }

      // Construct using com.hbase.protoc.SpatialAgg.SpatialAggRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        startTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        endTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        rowKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hbase.protoc.SpatialAgg.internal_static_SpatialAggRequest_descriptor;
      }

      public com.hbase.protoc.SpatialAgg.SpatialAggRequest getDefaultInstanceForType() {
        return com.hbase.protoc.SpatialAgg.SpatialAggRequest.getDefaultInstance();
      }

      public com.hbase.protoc.SpatialAgg.SpatialAggRequest build() {
        com.hbase.protoc.SpatialAgg.SpatialAggRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hbase.protoc.SpatialAgg.SpatialAggRequest buildPartial() {
        com.hbase.protoc.SpatialAgg.SpatialAggRequest result = new com.hbase.protoc.SpatialAgg.SpatialAggRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.startTime_ = startTime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.endTime_ = endTime_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.rowKey_ = rowKey_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hbase.protoc.SpatialAgg.SpatialAggRequest) {
          return mergeFrom((com.hbase.protoc.SpatialAgg.SpatialAggRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hbase.protoc.SpatialAgg.SpatialAggRequest other) {
        if (other == com.hbase.protoc.SpatialAgg.SpatialAggRequest.getDefaultInstance()) return this;
        if (other.hasStartTime()) {
          bitField0_ |= 0x00000001;
          startTime_ = other.startTime_;
          onChanged();
        }
        if (other.hasEndTime()) {
          bitField0_ |= 0x00000002;
          endTime_ = other.endTime_;
          onChanged();
        }
        if (other.hasRowKey()) {
          bitField0_ |= 0x00000004;
          rowKey_ = other.rowKey_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStartTime()) {
          
          return false;
        }
        if (!hasEndTime()) {
          
          return false;
        }
        if (!hasRowKey()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hbase.protoc.SpatialAgg.SpatialAggRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hbase.protoc.SpatialAgg.SpatialAggRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string startTime = 1;
      private java.lang.Object startTime_ = "";
      /**
       * <code>required string startTime = 1;</code>
       */
      public boolean hasStartTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string startTime = 1;</code>
       */
      public java.lang.String getStartTime() {
        java.lang.Object ref = startTime_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          startTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string startTime = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStartTimeBytes() {
        java.lang.Object ref = startTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          startTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string startTime = 1;</code>
       */
      public Builder setStartTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string startTime = 1;</code>
       */
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        startTime_ = getDefaultInstance().getStartTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string startTime = 1;</code>
       */
      public Builder setStartTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        startTime_ = value;
        onChanged();
        return this;
      }

      // required string endTime = 2;
      private java.lang.Object endTime_ = "";
      /**
       * <code>required string endTime = 2;</code>
       */
      public boolean hasEndTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string endTime = 2;</code>
       */
      public java.lang.String getEndTime() {
        java.lang.Object ref = endTime_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          endTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string endTime = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEndTimeBytes() {
        java.lang.Object ref = endTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          endTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string endTime = 2;</code>
       */
      public Builder setEndTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string endTime = 2;</code>
       */
      public Builder clearEndTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        endTime_ = getDefaultInstance().getEndTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string endTime = 2;</code>
       */
      public Builder setEndTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        endTime_ = value;
        onChanged();
        return this;
      }

      // required string rowKey = 3;
      private java.lang.Object rowKey_ = "";
      /**
       * <code>required string rowKey = 3;</code>
       */
      public boolean hasRowKey() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string rowKey = 3;</code>
       */
      public java.lang.String getRowKey() {
        java.lang.Object ref = rowKey_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          rowKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string rowKey = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRowKeyBytes() {
        java.lang.Object ref = rowKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rowKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string rowKey = 3;</code>
       */
      public Builder setRowKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        rowKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string rowKey = 3;</code>
       */
      public Builder clearRowKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rowKey_ = getDefaultInstance().getRowKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string rowKey = 3;</code>
       */
      public Builder setRowKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        rowKey_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SpatialAggRequest)
    }

    static {
      defaultInstance = new SpatialAggRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SpatialAggRequest)
  }

  public interface SpatialAggResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .SumMatrix sum = 1;
    /**
     * <code>repeated .SumMatrix sum = 1;</code>
     */
    java.util.List<com.hbase.protoc.SpatialAgg.SumMatrix> 
        getSumList();
    /**
     * <code>repeated .SumMatrix sum = 1;</code>
     */
    com.hbase.protoc.SpatialAgg.SumMatrix getSum(int index);
    /**
     * <code>repeated .SumMatrix sum = 1;</code>
     */
    int getSumCount();
    /**
     * <code>repeated .SumMatrix sum = 1;</code>
     */
    java.util.List<? extends com.hbase.protoc.SpatialAgg.SumMatrixOrBuilder> 
        getSumOrBuilderList();
    /**
     * <code>repeated .SumMatrix sum = 1;</code>
     */
    com.hbase.protoc.SpatialAgg.SumMatrixOrBuilder getSumOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code SpatialAggResponse}
   */
  public static final class SpatialAggResponse extends
      com.google.protobuf.GeneratedMessage
      implements SpatialAggResponseOrBuilder {
    // Use SpatialAggResponse.newBuilder() to construct.
    private SpatialAggResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SpatialAggResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SpatialAggResponse defaultInstance;
    public static SpatialAggResponse getDefaultInstance() {
      return defaultInstance;
    }

    public SpatialAggResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SpatialAggResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                sum_ = new java.util.ArrayList<com.hbase.protoc.SpatialAgg.SumMatrix>();
                mutable_bitField0_ |= 0x00000001;
              }
              sum_.add(input.readMessage(com.hbase.protoc.SpatialAgg.SumMatrix.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          sum_ = java.util.Collections.unmodifiableList(sum_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hbase.protoc.SpatialAgg.internal_static_SpatialAggResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hbase.protoc.SpatialAgg.internal_static_SpatialAggResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hbase.protoc.SpatialAgg.SpatialAggResponse.class, com.hbase.protoc.SpatialAgg.SpatialAggResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<SpatialAggResponse> PARSER =
        new com.google.protobuf.AbstractParser<SpatialAggResponse>() {
      public SpatialAggResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SpatialAggResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SpatialAggResponse> getParserForType() {
      return PARSER;
    }

    // repeated .SumMatrix sum = 1;
    public static final int SUM_FIELD_NUMBER = 1;
    private java.util.List<com.hbase.protoc.SpatialAgg.SumMatrix> sum_;
    /**
     * <code>repeated .SumMatrix sum = 1;</code>
     */
    public java.util.List<com.hbase.protoc.SpatialAgg.SumMatrix> getSumList() {
      return sum_;
    }
    /**
     * <code>repeated .SumMatrix sum = 1;</code>
     */
    public java.util.List<? extends com.hbase.protoc.SpatialAgg.SumMatrixOrBuilder> 
        getSumOrBuilderList() {
      return sum_;
    }
    /**
     * <code>repeated .SumMatrix sum = 1;</code>
     */
    public int getSumCount() {
      return sum_.size();
    }
    /**
     * <code>repeated .SumMatrix sum = 1;</code>
     */
    public com.hbase.protoc.SpatialAgg.SumMatrix getSum(int index) {
      return sum_.get(index);
    }
    /**
     * <code>repeated .SumMatrix sum = 1;</code>
     */
    public com.hbase.protoc.SpatialAgg.SumMatrixOrBuilder getSumOrBuilder(
        int index) {
      return sum_.get(index);
    }

    private void initFields() {
      sum_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < sum_.size(); i++) {
        output.writeMessage(1, sum_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < sum_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sum_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hbase.protoc.SpatialAgg.SpatialAggResponse)) {
        return super.equals(obj);
      }
      com.hbase.protoc.SpatialAgg.SpatialAggResponse other = (com.hbase.protoc.SpatialAgg.SpatialAggResponse) obj;

      boolean result = true;
      result = result && getSumList()
          .equals(other.getSumList());
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getSumCount() > 0) {
        hash = (37 * hash) + SUM_FIELD_NUMBER;
        hash = (53 * hash) + getSumList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hbase.protoc.SpatialAgg.SpatialAggResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.protoc.SpatialAgg.SpatialAggResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.protoc.SpatialAgg.SpatialAggResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.protoc.SpatialAgg.SpatialAggResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.protoc.SpatialAgg.SpatialAggResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.protoc.SpatialAgg.SpatialAggResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hbase.protoc.SpatialAgg.SpatialAggResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hbase.protoc.SpatialAgg.SpatialAggResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hbase.protoc.SpatialAgg.SpatialAggResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.protoc.SpatialAgg.SpatialAggResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hbase.protoc.SpatialAgg.SpatialAggResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SpatialAggResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hbase.protoc.SpatialAgg.SpatialAggResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hbase.protoc.SpatialAgg.internal_static_SpatialAggResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hbase.protoc.SpatialAgg.internal_static_SpatialAggResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hbase.protoc.SpatialAgg.SpatialAggResponse.class, com.hbase.protoc.SpatialAgg.SpatialAggResponse.Builder.class);
      }

      // Construct using com.hbase.protoc.SpatialAgg.SpatialAggResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSumFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (sumBuilder_ == null) {
          sum_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          sumBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hbase.protoc.SpatialAgg.internal_static_SpatialAggResponse_descriptor;
      }

      public com.hbase.protoc.SpatialAgg.SpatialAggResponse getDefaultInstanceForType() {
        return com.hbase.protoc.SpatialAgg.SpatialAggResponse.getDefaultInstance();
      }

      public com.hbase.protoc.SpatialAgg.SpatialAggResponse build() {
        com.hbase.protoc.SpatialAgg.SpatialAggResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hbase.protoc.SpatialAgg.SpatialAggResponse buildPartial() {
        com.hbase.protoc.SpatialAgg.SpatialAggResponse result = new com.hbase.protoc.SpatialAgg.SpatialAggResponse(this);
        int from_bitField0_ = bitField0_;
        if (sumBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            sum_ = java.util.Collections.unmodifiableList(sum_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.sum_ = sum_;
        } else {
          result.sum_ = sumBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hbase.protoc.SpatialAgg.SpatialAggResponse) {
          return mergeFrom((com.hbase.protoc.SpatialAgg.SpatialAggResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hbase.protoc.SpatialAgg.SpatialAggResponse other) {
        if (other == com.hbase.protoc.SpatialAgg.SpatialAggResponse.getDefaultInstance()) return this;
        if (sumBuilder_ == null) {
          if (!other.sum_.isEmpty()) {
            if (sum_.isEmpty()) {
              sum_ = other.sum_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSumIsMutable();
              sum_.addAll(other.sum_);
            }
            onChanged();
          }
        } else {
          if (!other.sum_.isEmpty()) {
            if (sumBuilder_.isEmpty()) {
              sumBuilder_.dispose();
              sumBuilder_ = null;
              sum_ = other.sum_;
              bitField0_ = (bitField0_ & ~0x00000001);
              sumBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSumFieldBuilder() : null;
            } else {
              sumBuilder_.addAllMessages(other.sum_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hbase.protoc.SpatialAgg.SpatialAggResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hbase.protoc.SpatialAgg.SpatialAggResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .SumMatrix sum = 1;
      private java.util.List<com.hbase.protoc.SpatialAgg.SumMatrix> sum_ =
        java.util.Collections.emptyList();
      private void ensureSumIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          sum_ = new java.util.ArrayList<com.hbase.protoc.SpatialAgg.SumMatrix>(sum_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.hbase.protoc.SpatialAgg.SumMatrix, com.hbase.protoc.SpatialAgg.SumMatrix.Builder, com.hbase.protoc.SpatialAgg.SumMatrixOrBuilder> sumBuilder_;

      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public java.util.List<com.hbase.protoc.SpatialAgg.SumMatrix> getSumList() {
        if (sumBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sum_);
        } else {
          return sumBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public int getSumCount() {
        if (sumBuilder_ == null) {
          return sum_.size();
        } else {
          return sumBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public com.hbase.protoc.SpatialAgg.SumMatrix getSum(int index) {
        if (sumBuilder_ == null) {
          return sum_.get(index);
        } else {
          return sumBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public Builder setSum(
          int index, com.hbase.protoc.SpatialAgg.SumMatrix value) {
        if (sumBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSumIsMutable();
          sum_.set(index, value);
          onChanged();
        } else {
          sumBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public Builder setSum(
          int index, com.hbase.protoc.SpatialAgg.SumMatrix.Builder builderForValue) {
        if (sumBuilder_ == null) {
          ensureSumIsMutable();
          sum_.set(index, builderForValue.build());
          onChanged();
        } else {
          sumBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public Builder addSum(com.hbase.protoc.SpatialAgg.SumMatrix value) {
        if (sumBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSumIsMutable();
          sum_.add(value);
          onChanged();
        } else {
          sumBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public Builder addSum(
          int index, com.hbase.protoc.SpatialAgg.SumMatrix value) {
        if (sumBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSumIsMutable();
          sum_.add(index, value);
          onChanged();
        } else {
          sumBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public Builder addSum(
          com.hbase.protoc.SpatialAgg.SumMatrix.Builder builderForValue) {
        if (sumBuilder_ == null) {
          ensureSumIsMutable();
          sum_.add(builderForValue.build());
          onChanged();
        } else {
          sumBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public Builder addSum(
          int index, com.hbase.protoc.SpatialAgg.SumMatrix.Builder builderForValue) {
        if (sumBuilder_ == null) {
          ensureSumIsMutable();
          sum_.add(index, builderForValue.build());
          onChanged();
        } else {
          sumBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public Builder addAllSum(
          java.lang.Iterable<? extends com.hbase.protoc.SpatialAgg.SumMatrix> values) {
        if (sumBuilder_ == null) {
          ensureSumIsMutable();
          super.addAll(values, sum_);
          onChanged();
        } else {
          sumBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public Builder clearSum() {
        if (sumBuilder_ == null) {
          sum_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          sumBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public Builder removeSum(int index) {
        if (sumBuilder_ == null) {
          ensureSumIsMutable();
          sum_.remove(index);
          onChanged();
        } else {
          sumBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public com.hbase.protoc.SpatialAgg.SumMatrix.Builder getSumBuilder(
          int index) {
        return getSumFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public com.hbase.protoc.SpatialAgg.SumMatrixOrBuilder getSumOrBuilder(
          int index) {
        if (sumBuilder_ == null) {
          return sum_.get(index);  } else {
          return sumBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public java.util.List<? extends com.hbase.protoc.SpatialAgg.SumMatrixOrBuilder> 
           getSumOrBuilderList() {
        if (sumBuilder_ != null) {
          return sumBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sum_);
        }
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public com.hbase.protoc.SpatialAgg.SumMatrix.Builder addSumBuilder() {
        return getSumFieldBuilder().addBuilder(
            com.hbase.protoc.SpatialAgg.SumMatrix.getDefaultInstance());
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public com.hbase.protoc.SpatialAgg.SumMatrix.Builder addSumBuilder(
          int index) {
        return getSumFieldBuilder().addBuilder(
            index, com.hbase.protoc.SpatialAgg.SumMatrix.getDefaultInstance());
      }
      /**
       * <code>repeated .SumMatrix sum = 1;</code>
       */
      public java.util.List<com.hbase.protoc.SpatialAgg.SumMatrix.Builder> 
           getSumBuilderList() {
        return getSumFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.hbase.protoc.SpatialAgg.SumMatrix, com.hbase.protoc.SpatialAgg.SumMatrix.Builder, com.hbase.protoc.SpatialAgg.SumMatrixOrBuilder> 
          getSumFieldBuilder() {
        if (sumBuilder_ == null) {
          sumBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.hbase.protoc.SpatialAgg.SumMatrix, com.hbase.protoc.SpatialAgg.SumMatrix.Builder, com.hbase.protoc.SpatialAgg.SumMatrixOrBuilder>(
                  sum_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          sum_ = null;
        }
        return sumBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:SpatialAggResponse)
    }

    static {
      defaultInstance = new SpatialAggResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SpatialAggResponse)
  }

  public interface SumMatrixOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated int32 array = 1;
    /**
     * <code>repeated int32 array = 1;</code>
     */
    java.util.List<java.lang.Integer> getArrayList();
    /**
     * <code>repeated int32 array = 1;</code>
     */
    int getArrayCount();
    /**
     * <code>repeated int32 array = 1;</code>
     */
    int getArray(int index);
  }
  /**
   * Protobuf type {@code SumMatrix}
   */
  public static final class SumMatrix extends
      com.google.protobuf.GeneratedMessage
      implements SumMatrixOrBuilder {
    // Use SumMatrix.newBuilder() to construct.
    private SumMatrix(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SumMatrix(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SumMatrix defaultInstance;
    public static SumMatrix getDefaultInstance() {
      return defaultInstance;
    }

    public SumMatrix getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SumMatrix(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                array_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              array_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                array_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                array_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          array_ = java.util.Collections.unmodifiableList(array_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hbase.protoc.SpatialAgg.internal_static_SumMatrix_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hbase.protoc.SpatialAgg.internal_static_SumMatrix_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hbase.protoc.SpatialAgg.SumMatrix.class, com.hbase.protoc.SpatialAgg.SumMatrix.Builder.class);
    }

    public static com.google.protobuf.Parser<SumMatrix> PARSER =
        new com.google.protobuf.AbstractParser<SumMatrix>() {
      public SumMatrix parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SumMatrix(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SumMatrix> getParserForType() {
      return PARSER;
    }

    // repeated int32 array = 1;
    public static final int ARRAY_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> array_;
    /**
     * <code>repeated int32 array = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getArrayList() {
      return array_;
    }
    /**
     * <code>repeated int32 array = 1;</code>
     */
    public int getArrayCount() {
      return array_.size();
    }
    /**
     * <code>repeated int32 array = 1;</code>
     */
    public int getArray(int index) {
      return array_.get(index);
    }

    private void initFields() {
      array_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < array_.size(); i++) {
        output.writeInt32(1, array_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < array_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(array_.get(i));
        }
        size += dataSize;
        size += 1 * getArrayList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hbase.protoc.SpatialAgg.SumMatrix)) {
        return super.equals(obj);
      }
      com.hbase.protoc.SpatialAgg.SumMatrix other = (com.hbase.protoc.SpatialAgg.SumMatrix) obj;

      boolean result = true;
      result = result && getArrayList()
          .equals(other.getArrayList());
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getArrayCount() > 0) {
        hash = (37 * hash) + ARRAY_FIELD_NUMBER;
        hash = (53 * hash) + getArrayList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hbase.protoc.SpatialAgg.SumMatrix parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.protoc.SpatialAgg.SumMatrix parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.protoc.SpatialAgg.SumMatrix parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.protoc.SpatialAgg.SumMatrix parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.protoc.SpatialAgg.SumMatrix parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.protoc.SpatialAgg.SumMatrix parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hbase.protoc.SpatialAgg.SumMatrix parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hbase.protoc.SpatialAgg.SumMatrix parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hbase.protoc.SpatialAgg.SumMatrix parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.protoc.SpatialAgg.SumMatrix parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hbase.protoc.SpatialAgg.SumMatrix prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SumMatrix}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hbase.protoc.SpatialAgg.SumMatrixOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hbase.protoc.SpatialAgg.internal_static_SumMatrix_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hbase.protoc.SpatialAgg.internal_static_SumMatrix_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hbase.protoc.SpatialAgg.SumMatrix.class, com.hbase.protoc.SpatialAgg.SumMatrix.Builder.class);
      }

      // Construct using com.hbase.protoc.SpatialAgg.SumMatrix.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        array_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hbase.protoc.SpatialAgg.internal_static_SumMatrix_descriptor;
      }

      public com.hbase.protoc.SpatialAgg.SumMatrix getDefaultInstanceForType() {
        return com.hbase.protoc.SpatialAgg.SumMatrix.getDefaultInstance();
      }

      public com.hbase.protoc.SpatialAgg.SumMatrix build() {
        com.hbase.protoc.SpatialAgg.SumMatrix result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hbase.protoc.SpatialAgg.SumMatrix buildPartial() {
        com.hbase.protoc.SpatialAgg.SumMatrix result = new com.hbase.protoc.SpatialAgg.SumMatrix(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          array_ = java.util.Collections.unmodifiableList(array_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.array_ = array_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hbase.protoc.SpatialAgg.SumMatrix) {
          return mergeFrom((com.hbase.protoc.SpatialAgg.SumMatrix)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hbase.protoc.SpatialAgg.SumMatrix other) {
        if (other == com.hbase.protoc.SpatialAgg.SumMatrix.getDefaultInstance()) return this;
        if (!other.array_.isEmpty()) {
          if (array_.isEmpty()) {
            array_ = other.array_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureArrayIsMutable();
            array_.addAll(other.array_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hbase.protoc.SpatialAgg.SumMatrix parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hbase.protoc.SpatialAgg.SumMatrix) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated int32 array = 1;
      private java.util.List<java.lang.Integer> array_ = java.util.Collections.emptyList();
      private void ensureArrayIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          array_ = new java.util.ArrayList<java.lang.Integer>(array_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 array = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getArrayList() {
        return java.util.Collections.unmodifiableList(array_);
      }
      /**
       * <code>repeated int32 array = 1;</code>
       */
      public int getArrayCount() {
        return array_.size();
      }
      /**
       * <code>repeated int32 array = 1;</code>
       */
      public int getArray(int index) {
        return array_.get(index);
      }
      /**
       * <code>repeated int32 array = 1;</code>
       */
      public Builder setArray(
          int index, int value) {
        ensureArrayIsMutable();
        array_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 array = 1;</code>
       */
      public Builder addArray(int value) {
        ensureArrayIsMutable();
        array_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 array = 1;</code>
       */
      public Builder addAllArray(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureArrayIsMutable();
        super.addAll(values, array_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 array = 1;</code>
       */
      public Builder clearArray() {
        array_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SumMatrix)
    }

    static {
      defaultInstance = new SumMatrix(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SumMatrix)
  }

  /**
   * Protobuf service {@code SpatialAggService}
   */
  public static abstract class SpatialAggService
      implements com.google.protobuf.Service {
    protected SpatialAggService() {}

    public interface Interface {
      /**
       * <code>rpc getSpatialAgg(.SpatialAggRequest) returns (.SpatialAggResponse);</code>
       */
      public abstract void getSpatialAgg(
          com.google.protobuf.RpcController controller,
          com.hbase.protoc.SpatialAgg.SpatialAggRequest request,
          com.google.protobuf.RpcCallback<com.hbase.protoc.SpatialAgg.SpatialAggResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new SpatialAggService() {
        @java.lang.Override
        public  void getSpatialAgg(
            com.google.protobuf.RpcController controller,
            com.hbase.protoc.SpatialAgg.SpatialAggRequest request,
            com.google.protobuf.RpcCallback<com.hbase.protoc.SpatialAgg.SpatialAggResponse> done) {
          impl.getSpatialAgg(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getSpatialAgg(controller, (com.hbase.protoc.SpatialAgg.SpatialAggRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.hbase.protoc.SpatialAgg.SpatialAggRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.hbase.protoc.SpatialAgg.SpatialAggResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc getSpatialAgg(.SpatialAggRequest) returns (.SpatialAggResponse);</code>
     */
    public abstract void getSpatialAgg(
        com.google.protobuf.RpcController controller,
        com.hbase.protoc.SpatialAgg.SpatialAggRequest request,
        com.google.protobuf.RpcCallback<com.hbase.protoc.SpatialAgg.SpatialAggResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.hbase.protoc.SpatialAgg.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getSpatialAgg(controller, (com.hbase.protoc.SpatialAgg.SpatialAggRequest)request,
            com.google.protobuf.RpcUtil.<com.hbase.protoc.SpatialAgg.SpatialAggResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.hbase.protoc.SpatialAgg.SpatialAggRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.hbase.protoc.SpatialAgg.SpatialAggResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.hbase.protoc.SpatialAgg.SpatialAggService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getSpatialAgg(
          com.google.protobuf.RpcController controller,
          com.hbase.protoc.SpatialAgg.SpatialAggRequest request,
          com.google.protobuf.RpcCallback<com.hbase.protoc.SpatialAgg.SpatialAggResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.hbase.protoc.SpatialAgg.SpatialAggResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.hbase.protoc.SpatialAgg.SpatialAggResponse.class,
            com.hbase.protoc.SpatialAgg.SpatialAggResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.hbase.protoc.SpatialAgg.SpatialAggResponse getSpatialAgg(
          com.google.protobuf.RpcController controller,
          com.hbase.protoc.SpatialAgg.SpatialAggRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.hbase.protoc.SpatialAgg.SpatialAggResponse getSpatialAgg(
          com.google.protobuf.RpcController controller,
          com.hbase.protoc.SpatialAgg.SpatialAggRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.hbase.protoc.SpatialAgg.SpatialAggResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.hbase.protoc.SpatialAgg.SpatialAggResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:SpatialAggService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SpatialAggRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SpatialAggRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SpatialAggResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SpatialAggResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SumMatrix_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SumMatrix_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021spatialAgg.protoc\"G\n\021SpatialAggRequest" +
      "\022\021\n\tstartTime\030\001 \002(\t\022\017\n\007endTime\030\002 \002(\t\022\016\n\006" +
      "rowKey\030\003 \002(\t\"-\n\022SpatialAggResponse\022\027\n\003su" +
      "m\030\001 \003(\0132\n.SumMatrix\"\032\n\tSumMatrix\022\r\n\005arra" +
      "y\030\001 \003(\0052M\n\021SpatialAggService\0228\n\rgetSpati" +
      "alAgg\022\022.SpatialAggRequest\032\023.SpatialAggRe" +
      "sponseB&\n\020com.hbase.protocB\nSpatialAggH\001" +
      "\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SpatialAggRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SpatialAggRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SpatialAggRequest_descriptor,
              new java.lang.String[] { "StartTime", "EndTime", "RowKey", });
          internal_static_SpatialAggResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_SpatialAggResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SpatialAggResponse_descriptor,
              new java.lang.String[] { "Sum", });
          internal_static_SumMatrix_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_SumMatrix_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SumMatrix_descriptor,
              new java.lang.String[] { "Array", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
